<a href="https://colab.research.google.com/github/mercariku/product-proposal/blob/main/MoneyTree_ProductProposal.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Table of contents

>[Table of contents](#scrollTo=y0lNbFOPXQvz)

>[New product proposal by Riku Driscoll](#scrollTo=ns82jDg95jra)

>>[Problem Statement](#scrollTo=kJcLmelxTzkx)

>>[Idea Statement](#scrollTo=fnlp0XXFZjzB)

>>[Discovery Activities](#scrollTo=90rIVHF4benU)

>>[Stakeholders / Business Strategy](#scrollTo=C2PjqfwrbxwL)

>>[Success Criteria](#scrollTo=zFeeLrC5b1Ye)

>>[Appendix](#scrollTo=tzEMkwQEb4pE)

>>>[If I had more time...](#scrollTo=tzEMkwQEb4pE)

>>>[Resource / Reference](#scrollTo=tzEMkwQEb4pE)

>[Import Datasets](#scrollTo=0a7_27cDW6Dz)

# New product proposal by Riku Driscoll

## Problem Statement

With the given datasets, there are several problems currently at large. 
- Explainability
  - Inability to explain (or infer) data
- Traceability
  - Unable to trace data without the help of other datasets
- Actionable insights
  - Given datasets provide only basic information and no intelligence (actionable insight)

## Idea Statement

- I propose to create a proprietary **MoneyTree Consumer Price Index** extended by the complimentary product, **Embedded CPI**
- The product is an Alternative Data as a Service, providing proprietary CPI data using a combination of MoneyTree datasets coupled with publicly available datasets. Unlike a traditional CPI, MCPI and EmbeddedCPI can also measure/gauge consumer sentiment (similar to the Michigan consumer sentiment index). 
- One of many usecases of the economic index is to help represent "the psychology of the entire [Japanese consumer behavior, sentiment] at any given moment. [MCPI] is an exact thmbprint of that moment." ([Reference to the show, Billions](https://www.reddit.com/r/Billions/comments/elr833/taylor_and_nasa_man_quote_failed_quant_hire/?utm_source=share&utm_medium=ios_app&utm_name=iossmf))
- The economic index would provide business intelligence to customers (in both private and public sectors, academic researchers, think tanks, etc.)
- In the private sector, the economic index would provide actionable intelligence, allowing organizations to review their business strategies and reallocate resources accordingly
- In the public sector, relevent government agencies can use the economic index as a signal to propose EBPM
- In the context of academic research, the economic index can be used to facilitate ongoing studies in econometrics (promoting collaboration with academics while improving the economic index)

## Discovery Activities

- Identifying roadmaps / milstones based on limited resources
- We must research the credibility of datasets, especially to minimize biases. The key is to expand and diversify data sources and corroborate to make sure the data is not skewed, etc. (i.e. age, location, payment method, etc) 
- Create a working model prototype to conduct a proof-of-concept trial to understand customer journies (In an attempt to point out any blind spots, or unknown unknowns & known unknowns)
- Research similar companies providing similar service (e.g. Nowcast, Macromoney) and create a business model that provides continuous stream of income with the ability to scale (while providing big enough moat to secure a position in the market)
- Identify deficiencies and prioritize resources: Can we create a product internally? or does a partnership make sense? (Thinking both short/medium and long run sucess)
- Identify points of failure. For example, what happens if datasource becomes unavailable for some reason?

## Stakeholders / Business Strategy
- Different stages of maturity will require different Stakeholders
- In the early stage, the team would rely heavily on engineers, econometric professionals, product managers (from other teams) and design researchers (UX/UI, academia, head of products, etc.). Here, the key is to repurpose as much resources as possible, as fast as possible, to operationalize and scale the product.
- During the growth stage, I believe, it's important to involve more senior members in the loop to help the product expand. Inevitably we would expand the engineering team to support added demand. Here, the key is to gain exposure and learn strengths and weaknesses of the product, allowing us to review strategies. Strategic transformation and change management can only happen with the help of senior members' input. 
- Once we reach a certain maturity, I believe, it's important to reassess each moving parts within the product to trim excess resources. The goal is to be easily maintainable and scalable (e.g. I propose a 100% serverless application on AWS using AWS SAM, an AWS native IaC to enable visibility, explainability and traceability). 
- Throughout every stage, it's imporatant to include compliance in the loop. My goal is to create a product that successfully influences the financial market, the consumer behavior, and government policy making. It's crucial to maintain sustainable growth by focusing on the "G" of ESG.
- In every stage, it's crucial to gain feedbacks internally AND externally while iterating the product to best suit customer needs.

## Success Criteria

- The goal is to "create products that help people & trusted organizations harness the power of data for good. Our plan for getting there is to deliver value through transparent insights that help people make clear financial decisions". 
- To gauge and measure product success, we would collect both qualitative and quantitive feedbacks
- Qualitative
  - Number of data source and partnerships (e.g. gauging credibility based on the number of "reviewers", "auditors")
  - Customer journey + time to impact (e.g. Getting feedbacks on usability)
  - The product would have a feature that allows users to trace specific data: Number of TRACE activity could indicate impact
- Quantitative
  - MAU (e.g. monitoring user access of Embedded CPI)
  - Number of projects (e.g. monitoring the number of projects the economic index is involved in)
  - Reliability (e.g. monitoring availability - or the downtime - to gauge technical reliability)
  - Adoption rate
  - Engagement rate, Retention rate
  - Return on Capital, Gross Margin
  - Impact
    - Empower organizations with actionable insights that enables investments of different kinds. 
    - Here, my ultimate goal is to create a small investment fund within MoneyTree that generates alternative revenue: The investment strategy hinged on the MCPI and Model Vector Autoregression.

## Appendix

### If I had more time...
- I'd conduct an ontology analysis and inference analysis to potentially discover correlations
- I'd bring other data sources (like location) to better understand user behavior
- I'd create a knowledge graph to easily identify relationships between transactions, etc. 
- I'd do more research on how to improve the data product lifecycle, so I can provide better answers to "Discovery activities" and "Stakeholders" sections. 

### Resource / Reference
- ["消費者物価指数の作り方"](https://www.stat.go.jp/data/cpi/2015/mikata/pdf/2.pdf)
- [Statistics Bureau of Japan](https://www.stat.go.jp/english/data/cpi/1585.html)
- [Mainstream CPIs around the world and assets affected by each CPI](https://www.avatrade.com/education/economic-indicators/fundamental-indicators/consumer-price-index)
- [IMF - CPI Manual - Concepts and Methods](https://www.imf.org/-/media/Files/Data/CPI/cpi-manual-concepts-and-methods.ashx)

# Import Datasets

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
import pandas as pd

df_past = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/datasets/past.csv")
display(df_past)

,date,description_raw,amount,created_at,updated_at,account_id,description_guest,description_pretty,category_id,expense_type,claim_id,expense_type_categorizer,id,raw_transaction_id
0,2019-07-17 15:00:00,フアミリ―マ―トトミタエキマエ,-100.0,2019-07-30 02:28:24.463617,2019-07-30 02:28:24.463617,13198024,NaN,フアミリ―マ―トトミタエキマエ,14,0,NaN,0,1644490565,1617410773
1,2019-07-19 15:00:00,すき家,-960.0,2019-07-30 02:28:06.799996,2019-07-30 02:28:06.799996,12135256,NaN,すき家,27,0,NaN,0,1644490010,1617410223
2,2019-07-26 15:00:00,ドン・キホーテ 八千代店,-3530.0,2019-07-30 02:29:43.488975,2019-07-30 02:29:43.488975,5797835,NaN,ドン・キホーテ 八千代店,40,0,NaN,0,1644492444,1617412636
3,2019-07-21 15:00:00,ソラシド エア インターネット,-23990.0,2019-07-30 02:28:22.028402,2019-07-30 02:28:22.028402,5719110,NaN,ソラシド エア インターネット,73,0,NaN,0,1644490516,1617410724
4,2019-08-12 15:00:00,手数料・利息,-6906.0,2019-07-30 02:29:46.443417,2019-07-30 02:29:46.443417,7625184,NaN,リボ払い 手数料,35,0,NaN,0,1644492519,1617412710
5,2019-07-24 15:00:00,大戸屋 阪急大井町ガーデン店,-1430.0,2019-07-30 02:29:55.618318,2019-07-30 02:29:55.618318,10449422,NaN,大戸屋 阪急大井町ガーデン店,40,0,NaN,0,1644492746,1617412934
6,2019-07-23 15:00:00,ペイペイ＊クスリノアオキ,-1195.0,2019-07-30 02:28:28.362856,2019-07-30 02:28:28.362856,7363778,NaN,ペイペイ*クスリノアオキ,40,0,NaN,0,1644490641,1617410849
7,2019-07-20 15:00:00,セブン－イレブン岐阜粟野西１丁目店／ｉＤ,-750.0,2019-07-30 02:29:56.008265,2019-07-30 02:29:56.008265,3843092,NaN,セブンーイレブン岐阜粟野西1丁目店/iD,14,0,NaN,0,1644492753,1617412942
8,2019-07-26 15:00:00,ＧＯＯＧＬＥ ＊ＬＩＮＥ ＣＯＲＰ,-240.0,2019-07-30 02:29:18.401709,2019-07-30 02:29:18.401709,10904426,NaN,GOOGLE *LINE CORP,26,0,NaN,0,1644491867,1617412067
9,2019-07-18 15:00:00,ﾒﾙｶﾘ /,-800.0,2019-07-30 02:28:34.354073,2019-07-30 02:28:34.354073,4217343,NaN,メルカリ /,12,0,NaN,0,1644490791,1617410995
10,2019-07-26 15:00:00,セイコーマート／ｉＤ,-430.0,2019-07-30 02:28:18.973712,2019-07-30 02:28:18.973712,11489596,NaN,セイコーマート/iD,14,0,NaN,0,1644490457,1617410666
11,2019-07-25 15:00:00,Ｙストア,-2178.0,2019-07-30 02:28:28.455192,2019-07-30 02:28:28.455192,7363778,NaN,Yストア,40,0,NaN,0,1644490645,1617410854
12,2019-07-19 15:00:00,スマートＥＸ（ＪＲ東海）,14070.0,2019-07-30 02:29:52.259414,2019-07-30 02:29:52.259414,747403,NaN,スマートEX(JR東海),71,0,NaN,0,1644492648,1617412836
13,2019-07-25 15:00:00,ＡＭＡＺＯＮ．ＣＯ．ＪＰ,-1243.0,2019-07-30 02:28:40.590553,2019-07-30 02:28:40.590553,1348128,NaN,AMAZON.CO.JP,11,0,NaN,0,1644491036,1617411236
14,2019-07-24 15:00:00,出光,-1400.0,2019-07-30 02:29:25.735863,2019-07-30 02:29:25.735863,11440101,NaN,出光,2,0,NaN,0,1644492041,1617412239
15,2019-07-20 15:00:00,Ｐ－ＴＡＬＫ,-6320.0,2019-07-30 02:28:43.864315,2019-07-30 02:28:43.864315,999316,NaN,P-TALK,95,0,NaN,0,1644491156,1617411356
16,2019-07-23 15:00:00,QP/ﾌｱﾐﾘｰﾏｰﾄ,-896.0,2019-07-30 02:28:35.93755,2019-07-30 02:28:35.93755,9654943,NaN,QP/フアミリーマート,14,0,NaN,0,1644490841,1617411042
17,2019-07-27 15:00:00,フアミリ－マ－トセイロカガ－デン,-296.0,2019-07-30 02:29:56.526303,2019-07-30 02:29:56.526303,10954653,NaN,フアミリーマートセイロカガーデン,14,0,NaN,0,1644492768,1617412953
18,2019-07-16 15:00:00,ｎａｎａｃｏクレジットチャージ,-6000.0,2019-07-30 02:29:05.790818,2019-07-30 02:29:05.790818,7806392,NaN,nanacoクレジットチャージ,94,0,NaN,0,1644491666,1617411872
19,2019-07-26 15:00:00,ＡＣＡＤＥＭＩＡ くまざわ書店,-907.0,2019-07-30 02:28:22.129979,2019-07-30 02:28:22.129979,5719110,NaN,ACADEMIA くまざわ書店,62,0,NaN,0,1644490525,1617410734
20,2019-07-26 15:00:00,ス－パ－ミラベルニシスガモテン,-2345.0,2019-07-30 02:29:08.255339,2019-07-30 02:29:08.255339,5007916,NaN,スーパーミラベルニシスガモテン,40,0,NaN,0,1644491730,1617411935
21,2019-07-25 15:00:00,出光興産 148866 02 37.00,-5550.0,2019-07-30 02:30:07.051884,2019-07-30 02:30:07.051884,9713655,NaN,出光興産 148762 02 37.00,2,0,NaN,0,1644492975,1617413158
22,2019-07-16 15:00:00,ジャパンタクシー,-3530.0,2019-07-30 02:29:31.08334,2019-07-30 02:29:31.08334,9461369,NaN,ジャパンタクシー,72,0,NaN,0,1644492210,1617412404
23,2019-07-22 15:00:00,ﾊﾞﾛ- ﾃﾞﾝﾎﾟｳｼﾞﾃﾝ,-1868.0,2019-07-30 02:29:29.597866,2019-07-30 02:29:29.597866,1316267,NaN,バロー デンポウジテン,40,0,NaN,0,1644492132,1617412327
24,2019-07-26 15:00:00,ｄ払いＢ スギ薬局グループ,-594.0,2019-07-30 02:28:23.388171,2019-07-30 02:28:23.388171,13391611,NaN,d払いB スギ薬局グループ,49,0,NaN,0,1644490544,1617410752
25,2019-07-23 15:00:00,華正樓 新館売店,-2700.0,2019-07-30 02:28:11.264036,2019-07-30 02:28:11.264036,8922546,NaN,華正樓 新館売店,80,0,NaN,0,1644490229,1617410439
26,2019-07-19 15:00:00,ｼﾈﾏｼﾃｲ,-2550.0,2019-07-30 02:29:30.495513,2019-07-30 02:29:30.495513,12855600,NaN,シネマシテイ,61,0,NaN,0,1644492177,1617412372
27,2019-07-22 15:00:00,STAATSOPER FUEHRUNGE WIEN,-2226.0,2019-07-30 02:29:33.846057,2019-07-30 02:29:33.846057,9461369,NaN,STAATSOPER FUEHRUNGE WIEN,55,0,NaN,0,1644492284,1617412477
28,2019-07-23 15:00:00,文化堂 豊洲店,-4212.0,2019-07-30 02:28:07.21484,2019-07-30 02:28:07.21484,12135256,NaN,文化堂 豊洲店,40,0,NaN,0,1644490027,1617410240
29,2019-07-19 15:00:00,ＡＭＡＺＯＮ．ＣＯ．ＪＰ,-2480.0,2019-07-30 02:28:40.785074,2019-07-30 02:28:40.785074,8286226,NaN,AMAZON.CO.JP,11,0,NaN,0,1644491046,1617411244
30,2019-07-26 15:00:00,ＣＨＩＬＤＲＥＮＳＡＬＯ（４４４８９２７７１１１０）,-17628.0,2019-07-30 02:29:48.123412,2019-07-30 02:29:48.123412,6015473,NaN,CHILDRENSALO(441892779110),95,0,NaN,0,1644492553,1617412743
31,2019-07-27 15:00:00,ファミリーマート／ｉＤ,-480.0,2019-07-30 02:29:23.799379,2019-07-30 02:29:23.799379,9025488,NaN,ファミリーマート/iD,14,0,NaN,0,1644491989,1617412187
32,2019-07-24 15:00:00,おさかな本舗たいこ茶屋,-15052.0,2019-07-30 02:28:07.33179,2019-07-30 02:28:07.33179,12135256,NaN,おさかな本舗たいこ茶屋,27,0,NaN,0,1644490030,1617410241
33,2019-07-24 15:00:00,クルメホテル エスプリ,-6804.0,2019-07-30 02:28:51.19219,2019-07-30 02:28:51.19219,12376424,NaN,クルメホテル エスプリ,82,0,NaN,2,1644491408,1617411621
34,2019-07-24 15:00:00,ヤフ－ウォレット決済＊クリックポ,-185.0,2019-07-30 02:28:35.401947,2019-07-30 02:28:35.401947,3351573,NaN,ヤフーウォレット決済*クリックポ,87,0,NaN,2,1644490821,1617411023
35,2019-07-23 15:00:00,UNTERES BELVEDERE WIEN,-1973.0,2019-07-30 02:29:34.628773,2019-07-30 02:29:34.628773,9461369,NaN,UNTERES BELVEDERE WIEN,52,0,NaN,0,1644492300,1617412493
36,2019-07-26 15:00:00,ＪＲ東日本モバイルＳｕｉｃａ,-2000.0,2019-07-30 02:28:27.350248,2019-07-30 02:28:27.350248,12381759,NaN,JR東日本モバイルSuica,71,0,NaN,0,1644490617,1617410825
37,2019-07-23 15:00:00,ＢＩＬＬ ＩＴＵＮＥＳ ＣＯＭ,-2650.0,2019-07-30 02:28:37.300829,2019-07-30 02:28:37.300829,11562478,NaN,BILL ITUNES COM,60,0,NaN,0,1644490896,1617411098
38,2019-07-24 15:00:00,ボンドガール ２ＮＤ,-8160.0,2019-07-30 02:28:40.542458,2019-07-30 02:28:40.542458,7969936,NaN,ボンドガール 2ND,95,0,NaN,0,1644491033,1617411232
39,2019-07-20 15:00:00,Ａｍａｚｏｎ Ｄｏｗｎｌｏａｄｓ,-1000.0,2019-07-30 02:28:26.5905,2019-07-30 02:28:26.5905,11102777,NaN,Amazon Downloads,62,0,NaN,0,1644490601,1617410809
40,2019-07-19 15:00:00,ﾒﾙｶﾘ /,-999.0,2019-07-30 02:28:34.50011,2019-07-30 02:28:34.50011,4217343,NaN,メルカリ /,12,0,NaN,0,1644490802,1617411005
41,2019-07-25 15:00:00,ＷＡＯＮオート,-3000.0,2019-07-30 02:29:50.087522,2019-07-30 02:29:50.087522,9089849,NaN,WAONオート,94,0,NaN,0,1644492594,1617412782
42,2019-07-26 15:00:00,キラヤ 大島店,-839.0,2019-07-30 02:29:52.387977,2019-07-30 02:29:52.387977,10067999,NaN,キラヤ 大島店,40,0,NaN,0,1644492655,1617412844
43,2019-07-14 15:00:00,太陽石油,-5132.0,2019-07-30 02:28:20.570154,2019-07-30 02:28:20.570154,8938123,NaN,太陽石油,2,0,NaN,0,1644490496,1617410705
44,2019-07-22 15:00:00,日本生命保険 相互会社,-13405.0,2019-07-30 02:28:17.972948,2019-07-30 02:28:17.972948,7363363,NaN,日本生命保険 相互会社,98,0,NaN,0,1644490438,1617410647
45,2019-07-22 15:00:00,小牧セントラルホテル,-8100.0,2019-07-30 02:29:52.442823,2019-07-30 02:29:52.442823,747403,NaN,小牧セントラルホテル,53,0,NaN,0,1644492660,1617412848
46,2019-07-20 15:00:00,マルエツプチ ニシシンジユクサンチヨウメ,-3217.0,2019-07-30 02:28:16.945915,2019-07-30 02:28:16.945915,13639525,NaN,マルエツプチ ニシシンジユクサンチヨウメ,40,0,NaN,0,1644490415,1617410624
47,2019-07-06 15:00:00,ＥＴＣ 関西支社,-690.0,2019-07-30 02:28:43.71698,2019-07-30 02:28:43.71698,999316,NaN,ETC 関西支社,7,0,NaN,0,1644491152,1617411351
48,2019-07-27 15:00:00,ローソン札幌北７条西一丁目,-541.0,2019-07-30 02:29:29.172414,2019-07-30 02:29:29.172414,12510840,NaN,ローソン札幌北7条西一丁目,14,0,NaN,0,1644492123,1617412319

In [4]:
df_recent = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/datasets/recent.csv")
display(df_recent)

,date,description_raw,amount,created_at,updated_at,account_id,description_guest,description_pretty,category_id,expense_type,claim_id,expense_type_categorizer,id,raw_transaction_id
0,2020-07-13 15:00:00,天下一品 天王寺店／ｉＤ,-1500.0,2020-07-17 02:27:20.556657,2020-07-17 02:27:20.556657,5942643,NaN,天下一品 天王寺店/iD,27,0,NaN,0,2544490000,2527899666
1,2020-07-06 15:00:00,楽天西友ネットスーパー 790001,-5959.0,2020-07-17 02:27:20.605587,2020-07-17 02:27:20.605587,13043578,NaN,楽天西友ネットスーパー 790007,40,0,NaN,0,2544490002,2527899668
2,2020-05-26 15:00:00,エポスカード ７月分家賃,-55000.0,2020-07-17 02:27:20.610542,2020-07-17 02:27:20.610542,18949857,NaN,エポスカード 7月分家賃,50,0,NaN,0,2544490003,2527899669
3,2020-07-14 15:00:00,フレスコ河原町丸太町店／ｉＤ,-751.0,2020-07-17 02:27:20.60067,2020-07-17 02:27:20.60067,5942643,NaN,フレスコ河原町丸太町店/iD,40,0,NaN,0,2544490005,2527899671
4,2020-07-14 15:00:00,ＡＭＡＺＯＮ．ＣＯ．ＪＰ,-3368.0,2020-07-17 02:27:20.639536,2020-07-17 02:27:20.639536,5942643,NaN,AMAZON.CO.JP,11,0,NaN,0,2544490007,2527899674
5,2020-07-06 15:00:00,楽天ＳＰ オーケー 川口店 722010,-6642.0,2020-07-17 02:27:20.667881,2020-07-17 02:27:20.667881,13043578,NaN,楽天SP オーケー 川口店 710010,40,0,NaN,0,2544490008,2527899673
6,2020-07-14 15:00:00,ＪＲ東日本 えきねっと,-15010.0,2020-07-17 02:27:20.664026,2020-07-17 02:27:20.664026,10526151,NaN,JR東日本 えきねっと,71,0,NaN,0,2544490009,2527899675
7,2020-05-26 15:00:00,エポスカード ７月分保証料,-820.0,2020-07-17 02:27:20.713364,2020-07-17 02:27:20.713364,18949857,NaN,エポスカード 7月分保証料,50,0,NaN,0,2544490011,2527899678
8,2020-07-14 15:00:00,ＡＭＡＺＯＮ．ＣＯ．ＪＰ,-3454.0,2020-07-17 02:27:20.685683,2020-07-17 02:27:20.685683,5942643,NaN,AMAZON.CO.JP,11,0,NaN,0,2544490012,2527899677
9,2020-07-09 15:00:00,ドミノ・ピザ 720197,-972.0,2020-07-17 02:27:20.737485,2020-07-17 02:27:20.737485,13043578,NaN,ドミノ・ピザ 720197,27,0,NaN,0,2544490013,2527899679
10,2020-07-14 15:00:00,ＪＲ東日本 えきねっと,-15010.0,2020-07-17 02:27:20.730288,2020-07-17 02:27:20.730288,10526151,NaN,JR東日本 えきねっと,71,0,NaN,0,2544490014,2527899680
11,2020-07-14 15:00:00,ソフトバンクＭ（０６月分）,-3479.0,2020-07-17 02:27:20.737402,2020-07-17 02:27:20.737402,5942643,NaN,ソフトバンクM(06月分),24,0,NaN,0,2544490016,2527899682
12,2020-07-11 15:00:00,ﾐｶｽﾞｷﾓﾓｺ,-1870.0,2020-07-17 02:27:20.80031,2020-07-17 02:27:20.80031,13043578,NaN,ミカズキモモコ,52,0,NaN,0,2544490017,2527899683
13,2020-06-26 15:00:00,エポスカード ８月分家賃,-55000.0,2020-07-17 02:27:20.809159,2020-07-17 02:27:20.809159,18949857,NaN,エポスカード 8月分家賃,50,0,NaN,0,2544490018,2527899684
14,2020-07-14 15:00:00,ＪＲ東日本 えきねっと,14690.0,2020-07-17 02:27:20.794985,2020-07-17 02:27:20.794985,10526151,NaN,JR東日本 えきねっと,71,0,NaN,0,2544490020,2527899687
15,2020-07-11 15:00:00,ｷﾞﾖｳﾑｽ-ﾊﾟ-ｶﾜｸﾞﾁｴ,-4918.0,2020-07-17 02:27:20.862482,2020-07-17 02:27:20.862482,13043578,NaN,ギヨウムスーパーカワグチエ,40,0,NaN,0,2544490022,2527899688
16,2020-07-14 15:00:00,ＪＲ東日本 えきねっと,14690.0,2020-07-17 02:27:20.851237,2020-07-17 02:27:20.851237,10526151,NaN,JR東日本 えきねっと,71,0,NaN,0,2544490023,2527899689
17,2020-06-26 15:00:00,エポスカード ８月分保証料,-820.0,2020-07-17 02:27:20.909862,2020-07-17 02:27:20.909862,18949857,NaN,エポスカード 8月分保証料,50,0,NaN,0,2544490025,2527899691
18,2020-07-12 15:00:00,三枚目助五郎 本宮店,-1100.0,2020-07-17 02:27:20.915715,2020-07-17 02:27:20.915715,10526151,NaN,三枚目助五郎 本宮店,95,0,NaN,0,2544490026,2527899694
19,2020-06-30 15:00:00,ヤマダプレミアムカイイン,-330.0,2020-07-17 02:27:21.092677,2020-07-17 02:27:21.092677,16044043,NaN,ヤマダプレミアムカイイン,35,0,NaN,0,2544490031,2527899697
20,2020-06-30 15:00:00,デイ－マガジン （ゲツガク）,-440.0,2020-07-17 02:27:21.139755,2020-07-17 02:27:21.139755,16044043,NaN,デイーマガジン (ゲツガク),62,0,NaN,0,2544490033,2527899699
21,2020-07-12 15:00:00,コスモ石油,-2000.0,2020-07-17 02:27:21.421559,2020-07-17 02:27:21.421559,14808352,NaN,コスモ石油,2,0,NaN,0,2544490039,2527899705
22,2020-07-14 15:00:00,ＭｏｎｏｔａＲＯ．ｃｏｍ,-8384.0,2020-07-17 02:27:21.453794,2020-07-17 02:27:21.453794,14808352,NaN,MonotaRO.com,49,0,NaN,0,2544490040,2527899706
23,2020-05-31 15:00:00,デユアルオプシヨンサービス,-1540.0,2020-07-17 02:27:21.633147,2020-07-17 02:27:21.633147,14763642,NaN,デユアルオプシヨンサービス,95,0,NaN,0,2544490046,2527899712
24,2020-07-26 15:00:00,手数料・利息,-6417.0,2020-07-17 02:27:21.701993,2020-07-17 02:27:21.701993,5805900,NaN,リボ払い 手数料,35,0,NaN,0,2544490050,2527899716
25,2020-06-17 15:00:00,ＴＳＵＴＡＹＡ ｏｎｌｉｎｅ,-7260.0,2020-07-17 02:27:21.725386,2020-07-17 02:27:21.725386,10295463,NaN,TSUTAYA online,62,0,NaN,0,2544490051,2527899717
26,2020-07-26 15:00:00,手数料・利息,-2360.0,2020-07-17 02:27:21.782313,2020-07-17 02:27:21.782313,5805900,NaN,キャッシング リボ払い 利息,35,0,NaN,0,2544490054,2527899721
27,2020-06-29 15:00:00,Ｕ－ＮＥＸＴ通信サービス利用料,-5071.0,2020-07-17 02:27:21.785895,2020-07-17 02:27:21.785895,14763642,NaN,U-NEXT通信サービス利用料,24,0,NaN,0,2544490058,2527899720
28,2020-06-17 15:00:00,ＴＳＵＴＡＹＡ ｏｎｌｉｎｅ,-11493.0,2020-07-17 02:27:21.839452,2020-07-17 02:27:21.839452,10295463,NaN,TSUTAYA online,62,0,NaN,0,2544490060,2527899726

In [8]:
arr_past = df_past["description_pretty"].unique()
for i in arr_past:
  print(i)

フアミリ―マ―トトミタエキマエ
すき家
ドン・キホーテ 八千代店
ソラシド エア インターネット
リボ払い 手数料
大戸屋 阪急大井町ガーデン店
ペイペイ*クスリノアオキ
セブンーイレブン岐阜粟野西1丁目店/iD
GOOGLE *LINE CORP
メルカリ /
セイコーマート/iD
Yストア
スマートEX(JR東海)
AMAZON.CO.JP
出光
P-TALK
QP/フアミリーマート
フアミリーマートセイロカガーデン
nanacoクレジットチャージ
ACADEMIA くまざわ書店
スーパーミラベルニシスガモテン
出光興産 148762 02 37.00
ジャパンタクシー
バロー デンポウジテン
d払いB スギ薬局グループ
華正樓 新館売店
シネマシテイ
STAATSOPER FUEHRUNGE WIEN
文化堂 豊洲店
CHILDRENSALO(441892779110)
ファミリーマート/iD
おさかな本舗たいこ茶屋
クルメホテル エスプリ
ヤフーウォレット決済*クリックポ
UNTERES BELVEDERE WIEN
JR東日本モバイルSuica
BILL ITUNES COM
ボンドガール 2ND
Amazon Downloads
WAONオート
キラヤ 大島店
太陽石油
日本生命保険 相互会社
小牧セントラルホテル
マルエツプチ ニシシンジユクサンチヨウメ
ETC 関西支社
ローソン札幌北7条西一丁目